### PR TITLE
Bump 3.32.2 release

### PR DESCRIPTION
**Pull request by igaldino**

### CODE REVIEW

**Comment by nedrichards** [comment]
Appdata validation failed!

> • attribute-invalid     : <screenshot> width did not match specified [https://gitlab.gnome.org/GNOME/gnome-notes/raw/master/data/appdata/default.png]
> • attribute-invalid     : <screenshot> height did not match specified [https://gitlab.gnome.org/GNOME/gnome-notes/raw/master/data/appdata/default.png]
> • attribute-invalid     : <screenshot> width did not match specified [https://gitlab.gnome.org/GNOME/gnome-notes/raw/master/data/appdata/edit.png]
> • attribute-invalid     : <screenshot> height did not match specified [https://gitlab.gnome.org/GNOME/gnome-notes/raw/master/data/appdata/edit.png]
> • attribute-invalid     : <screenshot> width did not match specified [https://gitlab.gnome.org/GNOME/gnome-notes/raw/master/data/appdata/list.png]
> • attribute-invalid     : <screenshot> height did not match specified [https://gitlab.gnome.org/GNOME/gnome-notes/raw/master/data/appdata/list.png]
> • attribute-invalid     : <screenshot> width did not match specified [https://gitlab.gnome.org/GNOME/gnome-notes/raw/master/data/appdata/select.png]
> • attribute-invalid     : <screenshot> height did not match specified [https://gitlab.gnome.org/GNOME/gnome-notes/raw/master/data/appdata/select.png]
> Validation of files failed

**Comment by igaldino** [comment]
@nedrichards yeah, I saw that.
I believe this is a new checking, right? Because the width and height of the pics weren't change, only the path in this release.
I'll add that checking to our CI in gitlab, to avoid that kind of problem in the future.
For now, can you please force that build? Is that possible? So users would have this version with screenshots instead of 3.32.0 which is missing that and some translations.
For 3.34 we'll probably have new screenshots, so I was not expecting to do that twice.
Thanks.

**Comment by nedrichards** [comment]
Sure, add a flathub.json file like this one to the PR and it'll skip the check: https://github.com/flathub/org.kde.okular/blob/master/flathub.json

If you want to run these tests in your CI then - awesome, great idea! The 'flathub' version of that is https://github.com/flathub/org.freedesktop.appstream-glib and you can install that as a flatpak from flathub in your CI if you wish!

**Comment by igaldino** [comment]
> Sure, add a flathub.json file like this one to the PR and it'll skip the check...
Great!

> If you want to run these tests in your CI...
I'll check that. Thanks!

**Pull request merged**
